### ISSUE TITLE
Erro 500 ao buscar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [bv-roberti/bootcamp-users#1]
Olá, meu nome é Alexandre e estou corrigindo sua atividade.

Trabalho aceito, parabéns! Para ficar 100%, sugiro incluir o tratamento de exceções. Está retornando erro 500 quando o id não existe. Tanto para a busca do cliente por id (GET), ao atualizar um cliente (UPDATE) e excluí-lo (DELETE).

Abraço e bons estudos

**Comment by bv-roberti** [comment]
Oi Alexandre, obrigado por corrigir.

Acabei de subir um merge com o ger de excecao

**Comment by bv-roberti** [comment]
https://github.com/bv-roberti/bootcamp-users/commit/ddd4dab6b7e18bf22b94051c91776e72ee69b0c0
